import type { Account, Supplier } from "./types"

export const mockAccounts: Account[] = [
  {
    id: "1",
    name: "Bank of Ceylon - Current Account",
    accountNumber: "1001",
    type: "Bank",
    currency: "LKR",
    balance: 2450000,
  },
  {
    id: "2",
    name: "Commercial Bank - USD Account",
    accountNumber: "1002",
    type: "Bank",
    currency: "USD",
    balance: 15000,
  },
  {
    id: "3",
    name: "Sampath Bank - Savings",
    accountNumber: "1003",
    type: "Bank",
    currency: "LKR",
    balance: 850000,
  },
  {
    id: "4",
    name: "Petty Cash",
    accountNumber: "1100",
    type: "Cash",
    currency: "LKR",
    balance: 50000,
  },
  {
    id: "5",
    name: "Cash on Hand - USD",
    accountNumber: "1101",
    type: "Cash",
    currency: "USD",
    balance: 500,
  },
  {
    id: "6",
    name: "Accounts Receivable",
    accountNumber: "1200",
    type: "Accounts Receivable",
    currency: "LKR",
    balance: 1250000,
  },
  {
    id: "7",
    name: "Prepaid Insurance",
    accountNumber: "1300",
    type: "Other Current",
    currency: "LKR",
    balance: 120000,
  },
  {
    id: "8",
    name: "Security Deposits",
    accountNumber: "1301",
    type: "Other Current",
    currency: "LKR",
    balance: 200000,
  },
  {
    id: "9",
    name: "Fixed Deposit - BOC",
    accountNumber: "1400",
    type: "Fixed Asset",
    currency: "LKR",
    balance: 5000000,
  },
  {
    id: "10",
    name: "Office Equipment",
    accountNumber: "1500",
    type: "Fixed Asset",
    currency: "LKR",
    balance: 850000,
  },
  {
    id: "11",
    name: "Computer & IT Equipment",
    accountNumber: "1501",
    type: "Fixed Asset",
    currency: "LKR",
    balance: 450000,
  },
  {
    id: "12",
    name: "Accounts Payable",
    accountNumber: "2000",
    type: "Accounts Payable",
    currency: "LKR",
    balance: -680000,
  },
  {
    id: "13",
    name: "VAT Payable",
    accountNumber: "2100",
    type: "Other Current Liability",
    currency: "LKR",
    balance: -125000,
  },
  {
    id: "14",
    name: "Salary Payable",
    accountNumber: "2101",
    type: "Other Current Liability",
    currency: "LKR",
    balance: -350000,
  },
  {
    id: "15",
    name: "Owner's Equity",
    accountNumber: "3000",
    type: "Equity",
    currency: "LKR",
    balance: 10000000,
  },
  {
    id: "16",
    name: "Sales Revenue",
    accountNumber: "4000",
    type: "Income",
    currency: "LKR",
    balance: 2450000,
  },
  {
    id: "17",
    name: "Service Revenue",
    accountNumber: "4001",
    type: "Income",
    currency: "LKR",
    balance: 850000,
  },
  {
    id: "18",
    name: "Cost of Goods Sold",
    accountNumber: "5000",
    type: "Cost of Goods Sold",
    currency: "LKR",
    balance: -1200000,
  },
  {
    id: "19",
    name: "Rent Expense",
    accountNumber: "6000",
    type: "Expense",
    currency: "LKR",
    balance: -150000,
  },
  {
    id: "20",
    name: "Salary Expense",
    accountNumber: "6001",
    type: "Expense",
    currency: "LKR",
    balance: -450000,
  },
  {
    id: "21",
    name: "Utilities Expense",
    accountNumber: "6002",
    type: "Expense",
    currency: "LKR",
    balance: -75000,
  },
  {
    id: "22",
    name: "Office Supplies",
    accountNumber: "6003",
    type: "Expense",
    currency: "LKR",
    balance: -35000,
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "ABC Suppliers Ltd",
    email: "contact@abcsuppliers.lk",
    phone: "+94 11 234 5678",
    address: "123 Main Street, Colombo 03",
    balance: 450000,
    currency: "LKR",
    status: "Active",
    totalPurchases: 450000,
  },
  {
    id: "2",
    name: "Global Tech Solutions",
    email: "info@globaltech.com",
    phone: "+94 11 876 5432",
    address: "45 Tech Park, Colombo 05",
    balance: 125000,
    currency: "USD",
    status: "Active",
    totalPurchases: 125000,
  },
  {
    id: "3",
    name: "Office Supplies Inc",
    email: "sales@officesupplies.lk",
    phone: "+94 11 555 6789",
    address: "78 Market Road, Colombo 07",
    balance: 85000,
    currency: "LKR",
    status: "Active",
    totalPurchases: 85000,
  },
  {
    id: "4",
    name: "Premier Equipment Co",
    email: "orders@premierequip.lk",
    phone: "+94 11 987 6543",
    address: "156 Industrial Zone, Colombo 10",
    balance: 320000,
    currency: "LKR",
    status: "Active",
    totalPurchases: 320000,
  },
  {
    id: "5",
    name: "International Traders",
    email: "contact@inttraders.com",
    phone: "+94 11 444 3333",
    address: "89 Export Lane, Colombo 02",
    balance: 25000,
    currency: "USD",
    status: "Inactive",
    totalPurchases: 25000,
  },
]

export const mockItems = [
  { id: "1", name: "Parson 4 Feet Warm White Tube light" },
  { id: "2", name: "LED Bulb 9W Cool White" },
  { id: "3", name: "LED Bulb 12W Warm White" },
  { id: "4", name: "T8 LED Tube 2 Feet" },
  { id: "5", name: "T8 LED Tube 4 Feet" },
  { id: "6", name: "Ceiling Light Round 18W" },
  { id: "7", name: "Panel Light 2x2 Feet" },
  { id: "8", name: "Panel Light 1x4 Feet" },
  { id: "9", name: "Street Light 50W" },
  { id: "10", name: "Flood Light 100W" },
  { id: "11", name: "Emergency Light LED" },
  { id: "12", name: "Solar Panel 100W" },
  { id: "13", name: "Battery 12V 100Ah" },
  { id: "14", name: "Inverter 1000W" },
  { id: "15", name: "Wire Cable 2.5mm" },
  { id: "16", name: "Wire Cable 4mm" },
  { id: "17", name: "Switch Socket 13A" },
  { id: "18", name: "MCB 32A Single Pole" },
  { id: "19", name: "Distribution Board 8 Way" },
  { id: "20", name: "LED Strip Light RGB 5M" },
]
